name: Eval e2e tests

on: [pull_request]

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Python version
        run: python --version
      - name: PDM installation
        run: pip install --user pdm
      - name: Install dependencies
        run: pdm install
      - name: Install devel dependencies
        run: pdm install --dev
      - name: Run integration e2e model evaluation tests
        run: pdm run pytest tests/e2e
        with:
          args: '--durations=0 -o junit_suite_name="rhoai_vllm" -m "model_evaluation" --junit-prefix="rhoai_vllm" --junit-xml="tests/test_results/junit_e2e_rhoai_vllm.xml" --eval_provider rhoai_vllm --eval_model granite3-8b --eval_out_dir tests/test_results --rp_name=ols-e2e-tests'
