name: Unit tests

on:
  - push
  - pull_request

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    strategy:
      matrix:
# Run tests only for Python 3.11 due to torch dependency.
#        python-version: ["3.11", "3.12", "3.13"]
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python version
        run: python --version
      - name: PDM installation
        run: pip install --user pdm
      - name: Install dependencies
        run: pdm install
      - name: Install devel dependencies
        run: pdm install --dev
      - name: Run unit tests
        run: pdm run python -m pytest tests/unit --cov=ols --cov=runner --cov-report term-missing
